backend:
  name: github
  repo: SPAZIO-GENESI/sito_sg_decap
  branch: main
  auth_type: repo  # Richiede token manuale
  client_id: Ov23liHhBJ2OIvs4V06t
  auth_endpoint: /api/auth
  base_url: https://spazio-genesi.github.io
  site_domain: "https://spazio-genesi.github.io"  # Il tuo URL GitHub Pages

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }