backend:
  name: github
  repo: SPAZIO-GENESI/sito_sg_decap
  branch: main
  local_backend: true  # Permette auth locale durante lo sviluppo
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts/blog"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }